{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "curity.fullname" . }}-ingress
  labels:
        {{- include "curity.labels" . | nindent 4 }}
        {{- with .Values.ingress.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
{{- if .Values.ingress.runtime.secretName }}
  tls:
    {{- if .Values.ingress.runtime.secretName }}
    - hosts:
      {{- if .Values.ingress.runtime.tlsHost }}
        - {{ .Values.ingress.runtime.tlsHost | quote }}
      {{- else }}
        - {{ .Values.ingress.runtime.host }}
      {{- end }}
      secretName: {{ .Values.ingress.runtime.secretName }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.runtime.host }}
      http:
        paths:
          {{- range .Values.ingress.runtime.paths }}
          - path: {{ . }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "curity.fullname" $ }}-runtime-svc
                port:
                  name: http-port
          {{- end }}
{{- if .Values.curity.config.uiEnabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "curity.fullname" . }}-ingress-admin
  labels:
        {{- include "curity.labels" . | nindent 4 }}
        {{- with .Values.ingress.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
{{- if .Values.ingress.admin.secretName }}
  tls:
    {{- if .Values.ingress.admin.secretName }}
    - hosts:
      {{- if .Values.ingress.admin.tlsHost }}
        - {{ .Values.ingress.admin.tlsHost | quote }}
      {{- else }}
        - {{ .Values.ingress.admin.host}}
      {{- end }}
      secretName: {{ .Values.ingress.admin.secretName }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.admin.host }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "curity.fullname" . }}-admin-svc
                port:
                  name: admin-ui
{{- end }}
{{- end }}
