{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "curity.fullname" . }}-ingress
  labels:
        {{- include "curity.labels" . | nindent 4 }}
        {{- with .Values.ingress.annotations }}
  annotations:
        {{- toYaml . | nindent 4 }}
        {{- end }}
spec:
{{- if or .Values.ingress.admin.secretName .Values.ingress.runtime.secretName }}
  tls:
    {{- if .Values.ingress.admin.secretName }}
    - hosts:
        - {{ .Values.ingress.admin.host}}
      secretName: {{ .Values.ingress.admin.secretName }}
    {{- end }}
    {{- if .Values.ingress.runtime.secretName }}
    - hosts:
        - {{ .Values.ingress.runtime.host}}
      secretName: {{ .Values.ingress.runtime.secretName }}
    {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.runtime.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "curity.fullname" . }}-runtime-svc
              servicePort: http-port
  {{- if .Values.curity.config.uiEnabled }}
    - host: {{ .Values.ingress.admin.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "curity.fullname" . }}-admin-svc
              servicePort: admin-ui
  {{- end }}
{{- end }}
